theme: jekyll-theme-time-machine
title: Fantastyczna strona Mai
description: Ta strona powstaje w ramach jednego z zadań mających na celu pogłębienie mojej wiedzy z zakresu narzędzi informatycznych :) cool
